"use client";

import { useState } from "react";
import useSWR from "swr";
import { Modal } from "@/components/ui/modal";
import { Button } from "@/components/ui/button";
import { apiGet, apiPost } from "@/lib/api-client";
import type { Company } from "@/types/models";
import type { PaginatedResponse } from "@/types/api";

interface GenerateResearchModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
}

export function GenerateResearchModal({
  isOpen,
  onClose,
  onSuccess,
}: GenerateResearchModalProps) {
  const [selectedCompanyId, setSelectedCompanyId] = useState("");
  const [briefType, setBriefType] = useState("company_summary");
  const [isLoading, setIsLoading] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");

  const { data: companiesData } = useSWR<PaginatedResponse<Company>>(
    isOpen ? "/companies?page=1&per_page=100" : null,
    (url: string) => apiGet<PaginatedResponse<Company>>(url)
  );

  const companies = companiesData?.items ?? [];

  const handleGenerate = async () => {
    if (!selectedCompanyId) {
      setError("Please select a company");
      return;
    }
    setIsLoading(true);
    setError("");
    setMessage("");
    try {
      await apiPost(`/research/company/${selectedCompanyId}`);
      setMessage("Research generation queued! It will appear shortly.");
      setTimeout(() => {
        onSuccess();
        onClose();
        setMessage("");
        setSelectedCompanyId("");
      }, 2000);
    } catch (err: unknown) {
      const msg =
        err instanceof Error ? err.message : "Failed to queue research";
      setError(msg);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Generate Research Brief"
      size="md"
      footer={
        <>
          <Button variant="outline" onClick={onClose} disabled={isLoading}>
            Cancel
          </Button>
          <Button onClick={handleGenerate} isLoading={isLoading}>
            Generate
          </Button>
        </>
      }
    >
      <div className="space-y-4">
        {error && (
          <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
            {error}
          </div>
        )}
        {message && (
          <div className="rounded-lg border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-700">
            {message}
          </div>
        )}

        <div>
          <label className="mb-1.5 block text-sm font-medium text-gray-700">
            Company *
          </label>
          <select
            value={selectedCompanyId}
            onChange={(e) => {
              setSelectedCompanyId(e.target.value);
              setError("");
            }}
            className="w-full rounded-lg border border-gray-300 bg-white px-3.5 py-2.5 text-sm text-gray-900 focus:border-primary-500 focus:outline-none focus:ring-2 focus:ring-primary-500/20"
          >
            <option value="">Select a company...</option>
            {companies.map((c) => (
              <option key={c.id} value={c.id}>
                {c.name}
              </option>
            ))}
          </select>
        </div>

        <div>
          <label className="mb-1.5 block text-sm font-medium text-gray-700">
            Brief Type
          </label>
          <select
            value={briefType}
            onChange={(e) => setBriefType(e.target.value)}
            className="w-full rounded-lg border border-gray-300 bg-white px-3.5 py-2.5 text-sm text-gray-900 focus:border-primary-500 focus:outline-none focus:ring-2 focus:ring-primary-500/20"
          >
            <option value="company_summary">Company Summary</option>
            <option value="talking_points">Talking Points</option>
            <option value="industry_brief">Industry Brief</option>
          </select>
        </div>

        <p className="text-xs text-gray-500">
          Research will be generated by AI and may take a few moments to
          complete.
        </p>
      </div>
    </Modal>
  );
}
